### PR TITLE
AP_Frsky_Telem: reverted loop code to scheduled task

### PR DESCRIPTION
**Pull request by yaapu**
Hi Chris, this should work just fine with nuttx.

### CODE REVIEW

**Comment by Chris-AC9KH** [comment]
@yaapu thanks! We will have to use this until we get these other control anomalies worked out with ChibiOS. Some further testing has revealed that it only affects fmuv2 and fmuv3 hardware. Possibly also fmuv4. We can't verify the problem on the F7 processor controllers (fmuv5).

I think I've narrowed it down to the IOMCU firmware for fmuv3. The IOMCU firmware is the same from fmuv2 to fmuv3 except for the USB ID's. This problem with the main loop locking up has been sporadic in ArduPilot as well. I tested with Copter 4.0 and had the same issue on fmuv3 hardware with both CUAV V3x and Pixhawk2.1 controllers. So for safety purposes we are going to stick with NuttX on those.

**Comment by Chris-AC9KH** [comment]
merged, thanks! Will report back on testing.

**Comment by Chris-AC9KH** [comment]
@yaapu turns out it may have not had anything to do with the scheduler. The FrSky telemetry is completely dead on NuttX, both passthru and SPort. So something was done in the HAL to break compatibility with NuttX from Copter 3.6.7 to 3.6.12. I'm suspecting to fix all the issues with ChibiOS serial ports. The rebase from 3.6.7 to 3.6.12 broke NuttX FrSky support completely.

Since we are not interested in ChibiOS at the present time, I'll have to revert back to the 3.6.7 codebase where HeliPilot was originally f()rked from ArduHeli 3.6.7 (which was another custom fork of Copter 3.6.7 for Copter heli new feature testing). Then it will work again.

Just to verify all this I loaded these changes into HeliPilot v19, which was the original fork of 3.6.7. The telemetry ran fine with this latest reversion from the loop code.

**Comment by Chris-AC9KH** [comment]
@yaapu after I reverted the codebase for the NuttX builds back to the Copter 3.6.7 version this worked perfectly fine. So for master with ChibiOS I did not apply this, it was only required for NuttX. I built some ChibiOS builds for F7 processor controllers for v20. I was not able to verify the IOMCU issue on F7-based controllers, only fmuv3 with STM32F4-based units. There is some sort of incompatibility there, and I'm not sure what it is. But we are sticking with the NuttX-based builds for our own heli's this year. We do not have time to debug ChibiOS so we'll let ChibiOS mature for another year and stick with proven builds in our equipment.

Thanks!

**Comment by yaapu** [comment]
@ChristopherOlson ok, the frsky telemetry enhancements I did should work just fine no matter the version

**Comment by Chris-AC9KH** [comment]
@yaapu that is correct. It was just a matter of gaining back the NuttX compatibility in the base Copter code that was lost sometime after Copter 3.6.7. I think it had something to do with changes in ChibiOS to fix the I2C "storm" issue on serial ports. But I didn't dig into it too much because that does not affect NuttX anyway.

**Comment by ChristopherOlson** [comment]
@yaapu I think when it became evident ChibiOS has a serious issue with the main loop locking up, and all the "watchdog" stuff, I2C "storm" issues, etc.. The decision was made to move forward and "patch" this stuff in ChibiOS and abandon NuttX compatibility in Copter stable after 3.6.7. That's when all the "watchdog" stuff and etc. happened.

That was actually the reason HeliPilot 19 is based on Copter 3.6.7. The Copter code became a spaghetti-code nightmare after that to "fix" ChibiOS.

**Pull request merged**
