### PR TITLE
AP_Frsky_Telem: added telemetry support for vfrhud message and rpm

### PR DESCRIPTION
**Pull request by yaapu**
This adds:
RPM 1 and 2 for  serial_protocol = 4
RPM 1 and 2 + VFRHUD for serial_protocol = 10

### CODE REVIEW

**Comment by Chris-AC9KH** [comment]
Hi Alex,
I will merge this later this evening since this is test code. I have the HeliPilot modded Yaapu that you did some time back. I think this will be pretty cool with that modded script, and finally fully-compatible with ArduPilot 4.0.x as well, since I know there is people that want it.

**Comment by yaapu** [comment]
Chris this is an updated version of the modded lua script https://drive.google.com/file/d/1k4PNrgoPMJklo2r5Jj8SGS9-sheYvfJ9/view?usp=sharing

**Comment by Chris-AC9KH** [comment]
Alex, ah thanks! I did not know you had an updated version of it.

**Comment by yaapu** [comment]
...made it today, it's brand new :)

**Comment by Chris-AC9KH** [comment]
@yaapu one thing I did do here that I did not do otherwise, is remove that Bad AHRS message, which is not a big deal but kind of annoying. It's only 4 lines of code in AP_Frsky_Telem.cpp but should not otherwise cause an issue (I don't think).

**Comment by Chris-AC9KH** [comment]
Merged! The rpm looked pretty simple, as I suspected. I see lots of corrections to remove whitespace :-) I had noticed that when I opened it in pico some time back and planned on cleaning those up, but you beat me to it!

**Pull request merged**
